"""
PDF export for the Health Passport.

Generates a clean, printable one-page PDF with all passport info, surgeries,
vaccinations, and the emergency QR code embedded -- so a physical printed
copy works exactly like the digital one for a doctor scanning it.

Uses fpdf2 (pure Python, no system dependencies like wkhtmltopdf/Chrome
needed -- important for easy deployment).
"""

import io
from fpdf import FPDF

PRIMARY_RGB = (15, 111, 255)      # #0F6FFF
SECONDARY_RGB = (16, 185, 129)    # #10B981
TEXT_RGB = (30, 41, 59)
MUTED_RGB = (100, 116, 139)


class PassportPDF(FPDF):
    def header(self):
        self.set_fill_color(*PRIMARY_RGB)
        self.rect(0, 0, 210, 22, style="F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 16)
        self.set_xy(10, 6)
        self.cell(0, 10, "VeriMed AI -- Health Passport", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_xy(10, 15)
        self.cell(0, 6, "Emergency Medical Information Card", new_x="LMARGIN", new_y="NEXT")
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*MUTED_RGB)
        self.cell(0, 10, "Generated by VeriMed AI. Educational project -- not a substitute for official medical records.", align="C")

    def section_title(self, title: str):
        self.ln(3)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*PRIMARY_RGB)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*PRIMARY_RGB)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def field_row(self, label: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*MUTED_RGB)
        self.cell(55, 7, label, new_x="RIGHT", new_y="TOP")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*TEXT_RGB)
        self.multi_cell(135, 7, value or "Not provided", new_x="LMARGIN", new_y="NEXT")


def generate_passport_pdf(passport: dict, surgeries: list[dict], vaccinations: list[dict], qr_png_bytes: bytes) -> bytes:
    pdf = PassportPDF(format="A4")
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ---- Personal details ----
    pdf.section_title("Personal Details")
    pdf.field_row("Full Name:", passport.get("full_name", ""))
    pdf.field_row("Date of Birth:", passport.get("date_of_birth", ""))
    pdf.field_row("Blood Group:", passport.get("blood_group", ""))

    # ---- Medical info ----
    pdf.section_title("Medical Information")
    pdf.field_row("Allergies:", passport.get("allergies") or "None listed")
    pdf.field_row("Chronic Conditions:", passport.get("chronic_conditions") or "None listed")
    pdf.field_row("Current Medicines:", passport.get("current_medicines") or "None listed")

    # ---- Surgeries ----
    pdf.section_title("Surgical History")
    if surgeries:
        for s in surgeries:
            pdf.field_row(f"{s['year']}:", s["description"])
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(*MUTED_RGB)
        pdf.cell(0, 7, "None recorded.", new_x="LMARGIN", new_y="NEXT")

    # ---- Vaccinations ----
    pdf.section_title("Vaccination Record")
    if vaccinations:
        for v in vaccinations:
            pdf.field_row(f"{v['month']} {v['year']}:", v["vaccine_name"])
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(*MUTED_RGB)
        pdf.cell(0, 7, "None recorded.", new_x="LMARGIN", new_y="NEXT")

    # ---- Emergency contact ----
    pdf.section_title("Emergency Contact")
    pdf.field_row("Name:", passport.get("emergency_contact_name", ""))
    pdf.field_row("Phone:", passport.get("emergency_contact_phone", ""))

    # ---- QR code ----
    pdf.section_title("Emergency QR Code")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTED_RGB)
    pdf.multi_cell(0, 6, "Scan this code to view this person's emergency medical summary instantly -- no app or login required.")
    pdf.ln(2)

    qr_stream = io.BytesIO(qr_png_bytes)
    pdf.image(qr_stream, x=10, y=pdf.get_y(), w=35, h=35)
    pdf.ln(40)

    output = pdf.output()
    return bytes(output)


if __name__ == "__main__":
    # Quick manual test -- run: python pdf_export.py
    import health_passport as hp
    import os

    if os.path.exists(hp.DB_FILE):
        os.remove(hp.DB_FILE)
    hp.init_passport_table()
    hp.save_passport(1, {
        "full_name": "Jane Doe", "blood_group": "O+", "date_of_birth": "01-01-1995",
        "allergies": "Penicillin", "chronic_conditions": "Asthma",
        "current_medicines": "Ventolin inhaler", "emergency_contact_name": "John Doe",
        "emergency_contact_phone": "+91-9999999999",
    })
    hp.add_surgery(1, "2019", "Appendectomy")
    hp.add_vaccination(1, "COVID-19 Booster", "March", "2024")

    passport = hp.get_passport(1)
    surgeries = hp.get_surgeries(1)
    vaccinations = hp.get_vaccinations(1)
    qr_bytes = hp.generate_qr_code(passport["share_token"], "http://localhost:5000")

    pdf_bytes = generate_passport_pdf(passport, surgeries, vaccinations, qr_bytes)

    with open("test_passport_output.pdf", "wb") as f:
        f.write(pdf_bytes)

    print(f"✅ PDF generated: {len(pdf_bytes)} bytes, saved to test_passport_output.pdf")
